name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Install rbenv & ruby-build
      run: |
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv 2>&1 \
        && cd ~/.rbenv \
        && src/configure \
        && make -C src \
        && bash -c "echo -e '\nif [ -d \"\$HOME/.rbenv/bin\" ] ; then\n    PATH=\"\$HOME/.rbenv/bin:\$PATH\"\nfi\n'" >> ~/.profile \
        && bash -c "echo -e 'eval \"\$(rbenv init -)\"\n\'" >> ~/.profile \
        && mkdir -p ~/.rbenv/plugins \
        && git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build        
    - name: Install ruby
      run: rbenv install 2.6.5
