name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: env
      run: env
    - name: Install rbenv & ruby-build
      run: |
        sudo apt-get update
        sudo apt-get -y install \
            autoconf \
            bison \
            build-essential \
            libssl-dev \
            libyaml-dev \
            libreadline6-dev \
            zlib1g-dev \
            libncurses5-dev \
            libffi-dev \
            libgdbm5 \
            libgdbm-dev
        git clone https://github.com/rbenv/ruby-build.git /tmp/ruby-build
        sudo PREFIX=/usr/local /tmp/ruby-build/install.sh
        ruby-build 2.6.5 /tmp/artifacts
        ls -la /tmp/artifacts
